# Generated by Django 2.1.2 on 2018-11-14 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20181114_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
