# Generated by Django 2.1.2 on 2018-11-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20181114_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='files/images/%Y/%m/%d/'),
        ),
    ]
