# Generated by Django 2.1.2 on 2018-11-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
