# Generated by Django 2.1.4 on 2019-03-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
