# Generated by Django 2.1.4 on 2019-03-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
