# Generated by Django 2.1.4 on 2019-03-07 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_auto_20190307_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadImage', to=settings.AUTH_USER_MODEL),
        ),
    ]
