# Generated by Django 2.1.4 on 2019-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_auto_20190307_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
